### ISSUE TITLE
Integration of a /roll command

### ISSUE THREAD

**Issue by chromamods** [Phibonacci/Total-Immersive-Chat-System#1]
Hi!

First of all, I think this addon is a fantastic addition for roleplay communities. It has some really great features, and feels fresh compared to alternative (but still great!) chat overhauls. 

That being said, I do have a suggestion. For roleplay communities out there who utilize roll combat, this addon makes it a bit difficult to do so. I was surprised when there was no roll command, or any evidence of one existing while exploring the project. Sadly, it's a dealbreaker for the inclusion in my community, as we rely heavily on dice to determine the outcome of certain encounters.

At some point, I am going to poke around and see about adding the functionality myself, then later submitting a pull request for the additions. However, that won't be for awhile as I have other priorities that take focus. In the mean time, if you think this is something you would like added into the addon, here was the command format I was looking to add:

/rolld dice bonus

For example, if I ran '/rolld 20 5', it would roll 1d20 and add 5 to the result. It would say something like:

"Chroma rolled a 1d20 (+5) and got a 15."

Thank you for your time, and again, great mod!

**Comment by Phibonacci** [comment]
That's an extremely trivial feature, I will add it once I'm done with some fixes.

```
/roll xdy
```

With x from 1 to 20 (I think that's big enough) and y without limit. Would output: `playerName rolled xdy (23, 12, 34, 54, 23, ...) = 3498`

So `/roll 2d20` could produce: `John Good rolled 2d20 (1, 4) = 5`

I'll make the random generator server side so people cannot hack their client to cheat it.

**Comment by Phibonacci** [comment]
It's done.

**Comment by Phibonacci** [comment]
I'll update it later with the [full dice notation](https://en.wikipedia.org/wiki/Dice_notation) so the following will work:

`/roll d20` to throw 1 dice of 20
`/roll 2d10+4` throw 2 dice of 10 then add 4 to the full result

**Comment by chromamods** [comment]
Awesome! Thank you for taking the idea and implementing it so quickly!

**Comment by Phibonacci** [comment]
I just updated the `/roll` command with the full dice notation. Enjoy!
