### ISSUE TITLE
[error] Using /me produces an error

### ISSUE THREAD

**Issue by Deide** [Phibonacci/Total-Immersive-Chat-System#3]
In the server console:

```
LOG  : General> TICS error: AuthorHasAccessByType has not method for type mesay
```

**Comment by Phibonacci** [comment]
Ah! There I was thinking I could just change a word somewhere without testing... and I forgot to update the server code as well. Sorry about that, I'm testing it and updating a fix in a few minutes.

**Comment by Phibonacci** [comment]
Well, it did not come from the server code in the end, but I fixed it anyway, it's on the workshop. Thank you for your report!

I'll remove those `/me*` commands later for an unique `/me` command instead with a `*` to prefix the produced message as you suggested. It would be easier to understand for everyone.
