### ISSUE TITLE
Chat Stream Flag When Using Radio

### ISSUE THREAD

**Issue by clay-garrard** [Phibonacci/Total-Immersive-Chat-System#4]
I am trying to figure out why the blue chat streams keep telling me "chat 'general' is disabled" **only** when I am using a radio. 
Radio Off, type /say test, message works normally 
Radio On, type /say test, Blue text flags, message still sends locally and over radio  

![Screenshot 2024-11-20 223332](https://github.com/user-attachments/assets/dd558ebc-81ca-410e-9380-c528045da8a7)
![Screenshot 2024-11-20 223351](https://github.com/user-attachments/assets/babd8745-5257-43f4-931d-bfe73bd30514)

Love the mod - great work

**Comment by Phibonacci** [comment]
I am not sure I understand. Are you reporting two different issue?

`/all` (`/g`) may be disable in the sandbox options, you can change them as an admin.

I don't understand the issue you are reporting with the radio. You are seeing the message twice to make it clear it went through the radio. I don't know if it was the best way to do it but that's on purpose.

Maybe I misinterpreted your report and there is a bug I don't see?

**Comment by clay-garrard** [comment]
Yes I am wondering why I am getting the "general chat is disabled" text. I
think i have it enabled.

What I found strange is that the flag only shows up when I am using a radio.

If my gen chat was disabled, wouldn't the flag also show when trying to gen
chat without the radio?

**Comment by Phibonacci** [comment]
I do not see any blue message related to `/all` on your screenshots. What am I missing?

**Comment by Phibonacci** [comment]
Feel free to reopen the issue if you can provide more information:

- A screenshot showing the error
- Or a video
- The content of both your client and server log files
