### ISSUE TITLE
Death message duplication with Knox Event Expanded

### ISSUE THREAD

**Issue by RegulaPlayer** [Phibonacci/Total-Immersive-Chat-System#6]
![image](https://github.com/user-attachments/assets/0b9e5327-4d88-45ae-b502-8bbbf5b045cc)

Any time a Player kills a Knox Event Expanded NPC, the death message for that NPC will show up Twice

**Comment by Phibonacci** [comment]
Maybe this mod was overriding the chat to remove the death message when it contained the name of a bot. Unless they support TICS on their side there is nothing I can do about it. I just print whatever server message I receive.

**Comment by RegulaPlayer** [comment]
Turns out the bug happens for admins only

**Comment by Phibonacci** [comment]
I am closing this issue as it does not seem to be directly related to TICS. Feel free to open it again if you think it is relevant.
